### ISSUE TITLE
adb: error: failed to stat remote object '/mnt/sdcard/coverage.x': No such file or directory

### ISSUE THREAD

**Issue by x4evexnol** [H2SO4T/ARES#16]
![image](https://user-images.githubusercontent.com/67748962/196368374-d1482def-2744-456e-8d32-e1eb4fa386d9.png)

**Comment by H2SO4T** [comment]
Hi,
I'm inventing an answer, as you have opened an issue without any context, no information about the app you are testing, if the app is instrumented and what version of Android you are using. 
Reading the screenshoot add can not find the file coverage.x 
Have you modified the code? because as you can see here: https://github.com/H2SO4T/ARES/blob/7ee16111c65a3f7cd5ebb39d4203c59d52ec04c7/rl_interaction/RL_application_env.py#L35 
that kind of file should have `.ec`extension 
)
Are you sure that you have instrumented the app? And again what instrumentation tool have you used?

**Comment by shiyuanxiang** [comment]
Thank you for your answer! Here is my configuration: Android version 11.0
I don't know how to instrument the app, I thought it could be done by ARES. So if I need to instrument app by myself, how should I do?

**Comment by H2SO4T** [comment]
No, ARES does not instrument the application, since it is a black-box tool and it does not rely on code coverage to explore the application under test.
If you you are not interested in collecting code coverage simply remove the `--instr_jacoco` flag or the `--instr_emma`, and ARES will test your app without collecting the code coverage

However, there are several ways to instrument an app. To automatically instrument apps from source code, you can use COSMO: https://github.com/H2SO4T/COSMO and that use ARES enabling ONLY the flag `--instr_jacoco`

**Comment by x4evexnol** [comment]
Thank you for your answer, I will try to fix it with your advice.
